title: Kwon MyeongEun
description: Android Engineer
site_title: 'Kwon MyeongEun'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: Kwon
blog_url: https://www.nagekar.com
email: abhishek@nagekar.com
keybase_username: Kwon
twitter_username: Kwon
reddit_username: Kwon

# absolute or relative
profile_picture: assets/images/pp.png

# Google Analytics ID
google_analytics: 